In [1]:
import pandas as pd
base = pd.read_csv('breast-cancer.csv')
base.head()

/home/m-joaopr/projetos/nlp/env/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


code_number  clump_thickness  uniformity_cell_size  uniformity_cell_shape  \
0      1000025                5                     1                      1   
1      1002945                5                     4                      4   
2      1015425                3                     1                      1   
3      1016277                6                     8                      8   
4      1017023                4                     1                      1   

   marginal_adhesion  single_epitelial_cell_size  bare_nuclei  \
0                  1                           2            1   
1                  5                           7           10   
2                  1                           2            2   
3                  1                           3            4   
4                  3                           2            1   

   bland_chromation  normal_nucleoli  mitoses   class  
0                 3                1        1  benign  
1                 3                2        1  benign  
2                 3                1        1  benign  
3                 3                7        1  benign  
4                 3                1        1  benign

In [2]:
base['mitoses'].unique()

array([ 1,  5,  4,  2,  3,  7, 10,  8,  6])

In [3]:
def converte_classe(rotulo):
    if rotulo == 'benign':
        return 1
    else:
        return 0

In [4]:
def unkown(rotulo):
    if rotulo == '?':
        return 0
    else:
        return rotulo

In [5]:
base['class'] = base['class'].apply(converte_classe)

In [6]:
base['bare_nuclei'] = base['bare_nuclei'].apply(unkown)

In [7]:
base.head()

code_number  clump_thickness  uniformity_cell_size  uniformity_cell_shape  \
0      1000025                5                     1                      1   
1      1002945                5                     4                      4   
2      1015425                3                     1                      1   
3      1016277                6                     8                      8   
4      1017023                4                     1                      1   

   marginal_adhesion  single_epitelial_cell_size  bare_nuclei  \
0                  1                           2            1   
1                  5                           7           10   
2                  1                           2            2   
3                  1                           3            4   
4                  3                           2            1   

   bland_chromation  normal_nucleoli  mitoses  class  
0                 3                1        1      1  
1                 3                2        1      1  
2                 3                1        1      1  
3                 3                7        1      1  
4                 3                1        1      1

In [8]:
base['class'].unique()

array([1, 0])

In [9]:
X = base.drop(['class', 'code_number'], axis = 1)

In [10]:
X.head()
type(X)

pandas.core.frame.DataFrame

In [11]:
y = base['class']

In [12]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [13]:
type(y)

pandas.core.series.Series

In [15]:
import tensorflow as tf

2021-10-13 10:30:07.645826: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-13 10:30:07.645890: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [16]:
X.columns

Index(['clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape',
       'marginal_adhesion', 'single_epitelial_cell_size', 'bare_nuclei',
       'bland_chromation', 'normal_nucleoli', 'mitoses'],
      dtype='object')

In [17]:
nome_colunas = ['clump_thickness', 'uniformity_cell_size', 'uniformity_cell_shape',
       'marginal_adhesion', 'single_epitelial_cell_size', 'bare_nuclei',
       'bland_chromation', 'normal_nucleoli', 'mitoses']

In [18]:
colunas = [ tf.feature_column.numeric_column(key = c) for c in nome_colunas ]

In [19]:
print(colunas)

[NumericColumn(key='clump_thickness', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='uniformity_cell_size', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='uniformity_cell_shape', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='marginal_adhesion', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='single_epitelial_cell_size', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='bare_nuclei', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='bland_chromation', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='normal_nucleoli', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='mitoses', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]


In [20]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [21]:
X_treinamento.shape
type(X_treinamento)

pandas.core.frame.DataFrame

In [22]:
X_teste.shape
type(y_treinamento)

pandas.core.series.Series

In [24]:
funcao_treinamento = tf.compat.v1.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [25]:
classificador = tf.estimator.LinearClassifier(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpmmhx6a1e', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [26]:
classificador.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


2021-10-13 10:32:43.822547: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-10-13 10:32:43.822666: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-13 10:32:43.822733: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (localhost): /proc/driver/nvidia/version does not exist


Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.


/home/m-joaopr/projetos/nlp/env/lib/python3.7/site-packages/keras/engine/base_layer_v1.py:1684: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.


2021-10-13 10:32:44.998110: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpmmhx6a1e/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.6931472, step = 0
INFO:tensorflow:global_step/sec: 517.019
INFO:tensorflow:loss = 0.18424237, step = 100 (0.194 sec)
INFO:tensorflow:global_step/sec: 808.445
INFO:tensorflow:loss = 0.09606165, step = 200 (0.125 sec)
INFO:tensorflow:global_step/sec: 770.73
INFO:tensorflow:loss = 0.10551812, step = 300 (0.129 sec)
INFO:tensorflow:global_step/sec: 772.735
INFO:tensorflow:loss = 0.23492764, step = 400 (0.128 sec)
INFO:tensorflow:global_step/sec: 781.359
INFO:tensorflow:loss = 0.052196976, step = 500 (0.129 sec)
INFO:tensorflow:global_step/sec: 788.005
INFO:tensorflow:loss = 0.058992

In [28]:
funcao_previsao = tf.compat.v1.estimator.inputs.pandas_input_fn(x = X_teste, batch_size = 32, shuffle = False)

In [29]:
previsoes = classificador.predict(input_fn=funcao_previsao)

In [30]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpmmhx6a1e/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'logits': array([-2.742423], dtype=float32),
  'logistic': array([0.06051597], dtype=float32),
  'probabilities': array([0.93948406, 0.060516  ], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'all_class_ids': array([0, 1], dtype=int32),
  'all_classes': array([b'0', b'1'], dtype=object)},
 {'logits': array([-6.7962275], dtype=float32),
  'logistic': array([0.00111672], dtype=float32),
  'probabilities': array([0.9988833 , 0.00111674], dtype=float32),
  'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'all_class_ids': array([0, 1], dtype=int32),
  'all_classes': array([b'0', b'1'], dtype=object)},
 {'logits': array([5.670985], dtype=float32),
  'logistic': array([0.99656737], dtype=float32),
  'probabilities': array([0.00343265, 0.99656737], dtype=float32),
  'class_ids': array([1]),
  'classes': array([b'1'], dtype=object),
  'all_class_ids': array([0, 1], dtype=int32),
  'all_classes': array([b'0', b'1'], dtype=object)},
 

In [31]:
previsoes_final = []
for p in classificador.predict(input_fn=funcao_previsao):
    previsoes_final.append(p['class_ids'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpmmhx6a1e/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [32]:
previsoes_final

[array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),

In [33]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste, previsoes_final)
taxa_acerto

0.9666666666666667